// feedback-autofix-comment.mjs の純粋関数に対する回帰テスト。
// Node 標準のテストランナーだけで動く（追加依存なし）:
//   npm run test:scripts
//
// 目印の綴りが壊れると重複検知が効かなくなり、同じ issue へ何度もコメントが
// 積まれる。理由の無害化と併せてここで固定する。

import assert from 'node:assert/strict';
import { test } from 'node:test';

import {
  MARKER,
  decideComment,
  parseVerdict,
  renderDeclineComment,
  renderLinkComment,
  sanitizeReason,
} from './feedback-autofix-comment.mjs';

test('PR が出来ていればリンクを返す', () => {
  const { action, body } = decideComment({
    prUrl: 'https://github.com/TrainLCD/MobileApp/pull/7002',
    verdict: null,
  });
  assert.equal(action, 'linked');
  assert.ok(body.startsWith(MARKER));
  assert.match(body, /pull\/7002/);
});

test('declined なら理由を添えて返す', () => {
  const { action, body } = decideComment({
    prUrl: '',
    verdict: { outcome: 'declined', reason: '路線記号は API が返す値です。', handoff: 'StationAPI' },
  });
  assert.equal(action, 'declined');
  assert.match(body, /直せないと判断しました/);
  assert.match(body, /路線記号は API が返す値です。/);
  assert.match(body, /TrainLCD\/StationAPI/);
});

test('PR がある場合は declined より PR を優先する', () => {
  const { action } = decideComment({
    prUrl: 'https://github.com/TrainLCD/MobileApp/pull/7002',
    verdict: { outcome: 'declined', reason: 'x', handoff: '' },
  });
  assert.equal(action, 'linked');
});

test('PR も判断も無ければコメントしない', () => {
  assert.equal(decideComment({ prUrl: '', verdict: null }).action, 'none');
  assert.equal(decideComment({ prUrl: '   ', verdict: null }).action, 'none');
});

test('fixed なのに PR が無い場合はコメントしない', () => {
  // 実行が途中で落ちた可能性がある。事実と違う記録を残すより黙るほうがよい。
  const { action } = decideComment({
    prUrl: '',
    verdict: { outcome: 'fixed', reason: '直しました', handoff: '' },
  });
  assert.equal(action, 'none');
});

test('verdict.json が壊れていても落ちない', () => {
  assert.equal(parseVerdict(''), null);
  assert.equal(parseVerdict('{'), null);
  assert.equal(parseVerdict('{"outcome":"unknown"}'), null);
  assert.equal(parseVerdict(undefined), null);
});

test('想定外の引き継ぎ先は捨てる', () => {
  assert.equal(parseVerdict('{"outcome":"declined","handoff":"evil.example"}').handoff, '');
  assert.equal(parseVerdict('{"outcome":"declined","handoff":"Functions"}').handoff, 'Functions');
});

test('理由に混ざった HTML コメントは落とす', () => {
  // 目印を偽装されると、次回の重複検知が誤作動する。
  assert.equal(sanitizeReason(`前${MARKER}後`), '前後');
  assert.equal(sanitizeReason('<!-- 何か -->理由'), '理由');
  assert.doesNotMatch(
    renderDeclineComment({ reason: sanitizeReason(`${MARKER}偽装`), handoff: '' })
      .replace(MARKER, ''),
    /auto-fix-from-feedback/
  );
});

test('理由は長すぎれば切り詰める', () => {
  assert.equal(sanitizeReason('あ'.repeat(2000)).length, 1200);
});

test('理由が空でもコメントは成立する', () => {
  const body = renderDeclineComment({ reason: '', handoff: '' });
  assert.match(body, /理由は記録されていません。/);
  assert.doesNotMatch(body, /対応先:/);
});

test('どのコメントも目印で始まり、出典表記で終わる', () => {
  for (const body of [
    renderLinkComment('https://example.invalid/pull/1'),
    renderDeclineComment({ reason: 'r', handoff: 'Functions' }),
  ]) {
    assert.ok(body.startsWith(MARKER));
    assert.match(body, /_Generated by \[Claude Code\]\(https:\/\/claude\.ai\/code\)_\n$/);
  }
});
