import {
  CompanyType,
  type Line,
  LineType,
  OperationStatus,
  type Station,
  StopCondition,
  TransportType,
} from '~/@types/graphql';

const JR_EAST_COMPANY = {
  __typename: 'Company' as const,
  id: 2,
  railroadId: 11,
  nameShort: 'JR東日本',
  nameKatakana: 'ジェイアールヒガシニホン',
  nameFull: '東日本旅客鉄道株式会社',
  nameEnglishShort: 'JR East',
  nameEnglishFull: 'JR East',
  type: CompanyType.Jr,
  status: OperationStatus.InOperation,
  name: 'JR東日本',
  url: 'http://www.jreast.co.jp/',
};

const YAMANOTE_LINE_SYMBOL = {
  symbol: 'JY',
  color: '#80C241',
  shape: 'SQUARE',
};

const yamanoteLineNested = {
  lineSymbols: [YAMANOTE_LINE_SYMBOL],
  id: 11302,
  nameShort: '山手線',
  nameKatakana: 'ヤマノテセン',
  nameFull: '山手線',
  nameRoman: 'Yamanote Line',
  nameChinese: '山手线',
  nameKorean: '야마노테선',
  color: '#80C241',
  lineType: LineType.Normal,
  status: OperationStatus.InOperation,
  transportType: TransportType.Rail,
  company: JR_EAST_COMPANY,
};

export const YAMANOTE_LINE = {
  __typename: 'Line' as const,
  ...yamanoteLineNested,
  averageDistance: undefined,
  trainType: undefined,
  station: undefined,
} as unknown as Line;

type StationDef = {
  id: number;
  groupId: number;
  name: string;
  nameKatakana: string;
  nameRoman: string;
  nameChinese: string;
  nameKorean: string;
  stationNumber: string;
  latitude: number;
  longitude: number;
  threeLetterCode?: string;
  prefectureId: number;
};

const stationDefs: StationDef[] = [
  {
    id: 1130224,
    groupId: 1130224,
    name: '東京',
    nameKatakana: 'トウキョウ',
    nameRoman: 'Tokyo',
    nameChinese: '东京',
    nameKorean: '도쿄',
    stationNumber: 'JY-01',
    latitude: 35.681391,
    longitude: 139.766103,
    threeLetterCode: 'TYO',
    prefectureId: 13,
  },
  {
    id: 1130202,
    groupId: 1130202,
    name: '神田',
    nameKatakana: 'カンダ',
    nameRoman: 'Kanda',
    nameChinese: '神田',
    nameKorean: '간다',
    stationNumber: 'JY-02',
    latitude: 35.691674,
    longitude: 139.770868,
    prefectureId: 13,
  },
  {
    id: 1130203,
    groupId: 1130203,
    name: '秋葉原',
    nameKatakana: 'アキハバラ',
    nameRoman: 'Akihabara',
    nameChinese: '秋叶原',
    nameKorean: '아키하바라',
    stationNumber: 'JY-03',
    latitude: 35.698356,
    longitude: 139.773288,
    threeLetterCode: 'AKB',
    prefectureId: 13,
  },
  {
    id: 1130204,
    groupId: 1130204,
    name: '御徒町',
    nameKatakana: 'オカチマチ',
    nameRoman: 'Okachimachi',
    nameChinese: '御徒町',
    nameKorean: '오카치마치',
    stationNumber: 'JY-04',
    latitude: 35.707282,
    longitude: 139.774729,
    prefectureId: 13,
  },
  {
    id: 1130220,
    groupId: 1130220,
    name: '上野',
    nameKatakana: 'ウエノ',
    nameRoman: 'Ueno',
    nameChinese: '上野',
    nameKorean: '우에노',
    stationNumber: 'JY-05',
    latitude: 35.713768,
    longitude: 139.777254,
    threeLetterCode: 'UEN',
    prefectureId: 13,
  },
  {
    id: 1130206,
    groupId: 1130206,
    name: '鶯谷',
    nameKatakana: 'ウグイスダニ',
    nameRoman: 'Uguisudani',
    nameChinese: '莺谷',
    nameKorean: '우구이스다니',
    stationNumber: 'JY-06',
    latitude: 35.720495,
    longitude: 139.778837,
    prefectureId: 13,
  },
  {
    id: 1130207,
    groupId: 1130207,
    name: '日暮里',
    nameKatakana: 'ニッポリ',
    nameRoman: 'Nippori',
    nameChinese: '日暮里',
    nameKorean: '닛포리',
    stationNumber: 'JY-07',
    latitude: 35.727772,
    longitude: 139.770987,
    threeLetterCode: 'NPR',
    prefectureId: 13,
  },
  {
    id: 1130221,
    groupId: 1130221,
    name: '西日暮里',
    nameKatakana: 'ニシニッポリ',
    nameRoman: 'Nishi-Nippori',
    nameChinese: '西日暮里',
    nameKorean: '니시닛포리',
    stationNumber: 'JY-08',
    latitude: 35.731954,
    longitude: 139.766857,
    prefectureId: 13,
  },
  {
    id: 1130209,
    groupId: 1130209,
    name: '田端',
    nameKatakana: 'タバタ',
    nameRoman: 'Tabata',
    nameChinese: '田端',
    nameKorean: '다바타',
    stationNumber: 'JY-09',
    latitude: 35.738063,
    longitude: 139.760872,
    prefectureId: 13,
  },
  {
    id: 1130210,
    groupId: 1130210,
    name: '駒込',
    nameKatakana: 'コマゴメ',
    nameRoman: 'Komagome',
    nameChinese: '�的込',
    nameKorean: '고마고메',
    stationNumber: 'JY-10',
    latitude: 35.736825,
    longitude: 139.747031,
    prefectureId: 13,
  },
  {
    id: 1130211,
    groupId: 1130211,
    name: '巣鴨',
    nameKatakana: 'スガモ',
    nameRoman: 'Sugamo',
    nameChinese: '巢鸭',
    nameKorean: '스가모',
    stationNumber: 'JY-11',
    latitude: 35.733445,
    longitude: 139.739303,
    prefectureId: 13,
  },
  {
    id: 1130222,
    groupId: 1130222,
    name: '大塚',
    nameKatakana: 'オオツカ',
    nameRoman: 'Otsuka',
    nameChinese: '大冢',
    nameKorean: '오쓰카',
    stationNumber: 'JY-12',
    latitude: 35.731412,
    longitude: 139.728584,
    prefectureId: 13,
  },
  {
    id: 1130212,
    groupId: 1130212,
    name: '池袋',
    nameKatakana: 'イケブクロ',
    nameRoman: 'Ikebukuro',
    nameChinese: '池袋',
    nameKorean: '이케부쿠로',
    stationNumber: 'JY-13',
    latitude: 35.729503,
    longitude: 139.710999,
    threeLetterCode: 'IKB',
    prefectureId: 13,
  },
  {
    id: 1130213,
    groupId: 1130213,
    name: '目白',
    nameKatakana: 'メジロ',
    nameRoman: 'Mejiro',
    nameChinese: '目白',
    nameKorean: '메지로',
    stationNumber: 'JY-14',
    latitude: 35.721204,
    longitude: 139.706587,
    prefectureId: 13,
  },
  {
    id: 1130214,
    groupId: 1130214,
    name: '高田馬場',
    nameKatakana: 'タカダノババ',
    nameRoman: 'Takadanobaba',
    nameChinese: '高田马场',
    nameKorean: '다카다노바바',
    stationNumber: 'JY-15',
    latitude: 35.712677,
    longitude: 139.703715,
    threeLetterCode: 'TBB',
    prefectureId: 13,
  },
  {
    id: 1130215,
    groupId: 1130215,
    name: '新大久保',
    nameKatakana: 'シンオオクボ',
    nameRoman: 'Shin-Okubo',
    nameChinese: '新大久保',
    nameKorean: '신오쿠보',
    stationNumber: 'JY-16',
    latitude: 35.700875,
    longitude: 139.700261,
    prefectureId: 13,
  },
  {
    id: 1130208,
    groupId: 1130208,
    name: '新宿',
    nameKatakana: 'シンジュク',
    nameRoman: 'Shinjuku',
    nameChinese: '新宿',
    nameKorean: '신주쿠',
    stationNumber: 'JY-17',
    latitude: 35.689729,
    longitude: 139.700464,
    threeLetterCode: 'SJK',
    prefectureId: 13,
  },
  {
    id: 1130216,
    groupId: 1130216,
    name: '代々木',
    nameKatakana: 'ヨヨギ',
    nameRoman: 'Yoyogi',
    nameChinese: '代代木',
    nameKorean: '요요기',
    stationNumber: 'JY-18',
    latitude: 35.683061,
    longitude: 139.702042,
    prefectureId: 13,
  },
  {
    id: 1130217,
    groupId: 1130217,
    name: '原宿',
    nameKatakana: 'ハラジュク',
    nameRoman: 'Harajuku',
    nameChinese: '原宿',
    nameKorean: '하라주쿠',
    stationNumber: 'JY-19',
    latitude: 35.670646,
    longitude: 139.702592,
    threeLetterCode: 'HRJ',
    prefectureId: 13,
  },
  {
    id: 1130205,
    groupId: 1130205,
    name: '渋谷',
    nameKatakana: 'シブヤ',
    nameRoman: 'Shibuya',
    nameChinese: '涩谷',
    nameKorean: '시부야',
    stationNumber: 'JY-20',
    latitude: 35.658517,
    longitude: 139.701334,
    threeLetterCode: 'SBY',
    prefectureId: 13,
  },
  {
    id: 1130218,
    groupId: 1130218,
    name: '恵比寿',
    nameKatakana: 'エビス',
    nameRoman: 'Ebisu',
    nameChinese: '惠比寿',
    nameKorean: '에비스',
    stationNumber: 'JY-21',
    latitude: 35.646685,
    longitude: 139.710071,
    prefectureId: 13,
  },
  {
    id: 1130219,
    groupId: 1130219,
    name: '目黒',
    nameKatakana: 'メグロ',
    nameRoman: 'Meguro',
    nameChinese: '目黑',
    nameKorean: '메구로',
    stationNumber: 'JY-22',
    latitude: 35.633923,
    longitude: 139.715775,
    prefectureId: 13,
  },
  {
    id: 1130223,
    groupId: 1130223,
    name: '五反田',
    nameKatakana: 'ゴタンダ',
    nameRoman: 'Gotanda',
    nameChinese: '五反田',
    nameKorean: '고탄다',
    stationNumber: 'JY-23',
    latitude: 35.625974,
    longitude: 139.723822,
    prefectureId: 13,
  },
  {
    id: 1130231,
    groupId: 1130231,
    name: '大崎',
    nameKatakana: 'オオサキ',
    nameRoman: 'Osaki',
    nameChinese: '大崎',
    nameKorean: '오사키',
    stationNumber: 'JY-24',
    latitude: 35.619772,
    longitude: 139.728439,
    prefectureId: 13,
  },
  {
    id: 1130229,
    groupId: 1130229,
    name: '品川',
    nameKatakana: 'シナガワ',
    nameRoman: 'Shinagawa',
    nameChinese: '品川',
    nameKorean: '시나가와',
    stationNumber: 'JY-25',
    latitude: 35.628471,
    longitude: 139.738716,
    threeLetterCode: 'SGW',
    prefectureId: 13,
  },
  {
    id: 1130225,
    groupId: 1130225,
    name: '高輪ゲートウェイ',
    nameKatakana: 'タカナワゲートウェイ',
    nameRoman: 'Takanawa Gateway',
    nameChinese: '高轮Gateway',
    nameKorean: '다카나와 게이트웨이',
    stationNumber: 'JY-26',
    latitude: 35.635493,
    longitude: 139.740121,
    prefectureId: 13,
  },
  {
    id: 1130226,
    groupId: 1130226,
    name: '田町',
    nameKatakana: 'タマチ',
    nameRoman: 'Tamachi',
    nameChinese: '田町',
    nameKorean: '다마치',
    stationNumber: 'JY-27',
    latitude: 35.645581,
    longitude: 139.747575,
    prefectureId: 13,
  },
  {
    id: 1130227,
    groupId: 1130227,
    name: '浜松町',
    nameKatakana: 'ハママツチョウ',
    nameRoman: 'Hamamatsucho',
    nameChinese: '浜松町',
    nameKorean: '하마마쓰초',
    stationNumber: 'JY-28',
    latitude: 35.655391,
    longitude: 139.757135,
    threeLetterCode: 'HMC',
    prefectureId: 13,
  },
  {
    id: 1130228,
    groupId: 1130228,
    name: '新橋',
    nameKatakana: 'シンバシ',
    nameRoman: 'Shimbashi',
    nameChinese: '新桥',
    nameKorean: '신바시',
    stationNumber: 'JY-29',
    latitude: 35.666379,
    longitude: 139.758296,
    threeLetterCode: 'SMB',
    prefectureId: 13,
  },
  {
    id: 1130230,
    groupId: 1130230,
    name: '有楽町',
    nameKatakana: 'ユウラクチョウ',
    nameRoman: 'Yurakucho',
    nameChinese: '有乐町',
    nameKorean: '유라쿠초',
    stationNumber: 'JY-30',
    latitude: 35.675441,
    longitude: 139.763073,
    prefectureId: 13,
  },
];

const buildStation = (def: StationDef): Station =>
  ({
    id: def.id,
    groupId: def.groupId,
    name: def.name,
    nameKatakana: def.nameKatakana,
    nameRoman: def.nameRoman,
    nameChinese: def.nameChinese,
    nameKorean: def.nameKorean,
    latitude: def.latitude,
    longitude: def.longitude,
    prefectureId: def.prefectureId,
    postalCode: undefined,
    address: undefined,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [
      {
        lineSymbol: 'JY',
        lineSymbolColor: '#80C241',
        lineSymbolShape: 'SQUARE',
        stationNumber: def.stationNumber,
      },
    ],
    stopCondition: StopCondition.All,
    threeLetterCode: def.threeLetterCode ?? undefined,
    hasTrainTypes: false,
    distance: undefined,
    transportType: TransportType.Rail,
    lines: [
      { ...yamanoteLineNested, station: undefined, trainType: undefined },
    ],
    line: { ...yamanoteLineNested, station: undefined, trainType: undefined },
    trainType: undefined,
  }) as unknown as Station;

/**
 * 山手線 全30駅（東京→有楽町、外回り順）
 * 実際の駅ID・座標を使用したリアルなフィクスチャデータ
 */
export const YAMANOTE_LINE_STATIONS: Station[] = stationDefs.map(buildStation);

/**
 * 外回り（OUTBOUND）用の方面駅（東京方面）
 */
export const YAMANOTE_OUTBOUND_BOUND = YAMANOTE_LINE_STATIONS[0]; // 東京

/**
 * 内回り（INBOUND）用の方面駅（東京方面の反対、有楽町方面）
 */
export const YAMANOTE_INBOUND_BOUND =
  YAMANOTE_LINE_STATIONS[YAMANOTE_LINE_STATIONS.length - 1]; // 有楽町

/**
 * 各テーマでのテストに使う代表的な駅（新宿: index 16）
 */
export const YAMANOTE_SHINJUKU = YAMANOTE_LINE_STATIONS[16];
export const YAMANOTE_SHIBUYA = YAMANOTE_LINE_STATIONS[19];
export const YAMANOTE_TOKYO = YAMANOTE_LINE_STATIONS[0];
export const YAMANOTE_IKEBUKURO = YAMANOTE_LINE_STATIONS[12];
export const YAMANOTE_UENO = YAMANOTE_LINE_STATIONS[4];
export const YAMANOTE_SHINAGAWA = YAMANOTE_LINE_STATIONS[24];
