export const MARK_SHAPE = {
  NOOP: 'NOOP',
  ROUND: 'ROUND',
  ROUND_HORIZONTAL: 'ROUND_HORIZONTAL',
  REVERSED_ROUND: 'REVERSED_ROUND',
  REVERSED_ROUND_HORIZONTAL: 'REVERSED_ROUND_HORIZONTAL',
  MONOCHROME_ROUND: 'MONOCHROME_ROUND',
  SQUARE: 'SQUARE',
  REVERSED_SQUARE: 'REVERSED_SQUARE',
  REVERSED_SQUARE_DARK_TEXT: 'REVERSED_SQUARE_DARK_TEXT',
  REVERSED_SQUARE_WEST: 'REVERSED_SQUARE_WEST',
  REVERSED_SQUARE_WEST_DARK_TEXT: 'REVERSED_SQUARE_WEST_DARK_TEXT',
  REVERSED_SQUARE_HORIZONTAL: 'REVERSED_SQUARE_HORIZONTAL',
  HALF_SQUARE: 'HALF_SQUARE',
  HALF_SQUARE_WITHOUT_ROUND: 'HALF_SQUARE_WITHOUT_ROUND',
  HALF_SQUARE_DARK_TEXT: 'HALF_SQUARE_DARK_TEXT',
  ODAKYU: 'ODAKYU',
  HAKONE: 'HAKONE',
  KEIO: 'KEIO',
  TWR: 'TWR',
  NEW_SHUTTLE: 'NEW_SHUTTLE',
  KEIKYU: 'KEIKYU',
  KINTETSU: 'KINTETSU',
  NANKAI: 'NANKAI',
  KEIHAN: 'KEIHAN',
  HANKYU: 'HANKYU',
  HANSHIN: 'HANSHIN',
  SANYO: 'SANYO',
  JR_UNION: 'JR_UNION',
  BULLET_TRAIN_UNION: 'BULLET_TRAIN_UNION',
  NUMBER_ONLY: 'NUMBER_ONLY',
  KEISEI: 'KEISEI',
  NTL: 'NTL',
  SMR: 'SMR',
  NISHITETSU: 'NISHITETSU',
  IZUHAKONE: 'IZUHAKONE',
} as const;

export const NUMBERING_ICON_SIZE = {
  LARGE: 'LARGE',
  MEDIUM: 'MEDIUM',
  SMALL: 'SMALL',
} as const;

// large: ヘッダーに使う
// medium: 乗り換え案内に使う
// small: タブレット用LineBoardに使う
export type NumberingIconSize =
  (typeof NUMBERING_ICON_SIZE)[keyof typeof NUMBERING_ICON_SIZE];

export const ROUND_SHAPES = new Set<string>([
  MARK_SHAPE.ROUND,
  MARK_SHAPE.REVERSED_ROUND,
  MARK_SHAPE.MONOCHROME_ROUND,
  MARK_SHAPE.ROUND_HORIZONTAL,
  MARK_SHAPE.REVERSED_ROUND_HORIZONTAL,
  MARK_SHAPE.KEIO,
  MARK_SHAPE.TWR,
  MARK_SHAPE.KEISEI,
  MARK_SHAPE.HANKYU,
  MARK_SHAPE.HANSHIN,
  MARK_SHAPE.IZUHAKONE,
]);
