export const REMOTE_CONFIG_KEYS = {
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  REPORT_LETTERS_LOWER_LIMIT: 'REPORT_LETTERS_LOWER_LIMIT',
  MAXIMUM_DAILY_FEEDBACK_COUNT: 'MAXIMUM_DAILY_FEEDBACK_COUNT',
} as const

export const REMOTE_CONFIG_PLACEHOLDERS = {
  UNDER_MAINTENANCE: false,
  REPORT_LETTERS_LOWER_LIMIT: 0,
  MAXIMUM_DAILY_FEEDBACK_COUNT: 5,
}
