source "https://rubygems.org"

gem "fastlane", "~> 2.228.0"
gem "abbrev", "~> 0.1"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
