require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'TrainLCD' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment to opt-in to using Flipper
  #
  if !ENV['CI']
    use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
    post_install do |installer|
      installer.pods_project.build_configurations.each do |build_configuration|
        build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'No'
      end
      installer.aggregate_targets.each do |aggregate_target|
        aggregate_target.xcconfigs.each do |config_name, config_file|
          config_file.attributes['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] ='arm64'
          config_file.save_as(aggregate_target.xcconfig_path(config_name))
        end
      end
      flipper_post_install(installer)
    end
  end
end

