require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

abstract_target 'TrainLCD' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    plist_buddy = '/usr/libexec/PlistBuddy'
    info_plists_to_clean = [File.join(__dir__, 'WatchApp', 'Info.plist')]

    [
      'WatchApp/Schemes',
      'WatchApp Extension/Schemes',
      'WatchWidget/Schemes',
      'RideSessionActivity/Schemes',
    ].each do |relative_dir|
      info_plists_to_clean.concat Dir[File.join(__dir__, relative_dir, '*', 'Info.plist')]
    end

    info_plists_to_clean.each do |plist_path|
      next unless File.exist?(plist_path)
      next unless system(plist_buddy, '-c', 'Print :RCTNewArchEnabled', plist_path, out: File::NULL, err: File::NULL)

      system(plist_buddy, '-c', 'Delete :RCTNewArchEnabled', plist_path)
    end
  end

  target 'ProdTrainLCD' do
    target 'ProdAppClip' do
      inherit! :complete
    end
  end

  target 'CanaryTrainLCD' do
    target 'CanaryAppClip' do
      inherit! :complete
    end
  end
end
