# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bump version number"
  lane :bump_version do
    increment_build_number(xcodeproj: "TrainLCD.xcodeproj")
  end
  desc "Push a new beta build to TestFlight"
  lane :deploy do
    match(
      type: "appstore",
      readonly: is_ci,
      app_identifier: [
        "me.tinykitten.trainlcd",
        "me.tinykitten.trainlcd.watchkitapp",
        "me.tinykitten.trainlcd.watchkitapp.watchkitextension",
        "me.tinykitten.trainlcd.ridesessionactivity"
      ],
      force_for_new_devices: true
    )
    gym(workspace: "TrainLCD.xcworkspace", scheme: "TrainLCD")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
