import { Station } from '~/gen/proto/stationapi_pb';

export const AMAGASAKI_STATIONS_FROM_SEARCH: Station[] = [
  {
    id: 1160303,
    groupId: 1160303,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: '',
    lines: [
      {
        id: 11603,
        nameShort: 'JR神戸線',
        nameKatakana: 'コウベセン',
        nameFull: '東海道本線',
        nameRoman: 'JR Kobe Line',
        nameChinese: 'JR神户线',
        nameKorean: 'JR 고베선',
        color: '#0072BC',
        lineType: 2,
        lineSymbols: [
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1160303,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'A',
              lineSymbolColor: '#0072BC',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'A-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15281,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11625,
        nameShort: 'JR東西線',
        nameKatakana: 'トウザイセン',
        nameFull: 'JR東西線',
        nameRoman: 'JR Tozai Line',
        nameChinese: 'JR东西线',
        nameKorean: 'JR 도자이선',
        color: '#FF1493',
        lineType: 2,
        lineSymbols: [
          { symbol: 'H', color: '#FF1493', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162509,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'H',
              lineSymbolColor: '#FF1493',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'H-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 17208,
            typeId: 100,
            groupId: 468,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11629,
        nameShort: 'JR宝塚線',
        nameKatakana: 'タカラヅカセン',
        nameFull: '福知山線',
        nameRoman: 'JR Takarazuka Line',
        nameChinese: 'JR宝冢线',
        nameKorean: 'JR 다카라즈카선',
        color: '#FFCC00',
        lineType: 2,
        lineSymbols: [
          {
            symbol: 'G',
            color: '#FFBA00',
            shape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
          },
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162903,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '쓰카모토',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'G',
              lineSymbolColor: '#FFBA00',
              lineSymbolShape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
              stationNumber: 'G-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15282,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11603,
      nameShort: 'JR神戸線',
      nameKatakana: 'コウベセン',
      nameFull: '東海道本線',
      nameRoman: 'JR Kobe Line',
      nameChinese: 'JR神户线',
      nameKorean: 'JR 고베선',
      color: '#0072BC',
      lineType: 2,
      lineSymbols: [
        { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1160303,
        groupId: 1160303,
        name: '尼崎',
        nameKatakana: 'アマガサキ',
        nameRoman: 'Amagasaki',
        nameChinese: '尼崎',
        nameKorean: '아마가사키',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '660-0808',
        address: '兵庫県尼崎市潮江一丁目1-1',
        latitude: 34.731791,
        longitude: 135.431685,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 28,
    postalCode: '660-0808',
    address: '兵庫県尼崎市潮江一丁目1-1',
    latitude: 34.731791,
    longitude: 135.431685,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'A',
        lineSymbolColor: '#0072BC',
        lineSymbolShape: 'REVERSED_SQUARE_WEST',
        stationNumber: 'A-49',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 15281,
      typeId: 100,
      groupId: 407,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 1162509,
    groupId: 1160303,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: '',
    lines: [
      {
        id: 11603,
        nameShort: 'JR神戸線',
        nameKatakana: 'コウベセン',
        nameFull: '東海道本線',
        nameRoman: 'JR Kobe Line',
        nameChinese: 'JR神户线',
        nameKorean: 'JR 고베선',
        color: '#0072BC',
        lineType: 2,
        lineSymbols: [
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1160303,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'A',
              lineSymbolColor: '#0072BC',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'A-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15281,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11625,
        nameShort: 'JR東西線',
        nameKatakana: 'トウザイセン',
        nameFull: 'JR東西線',
        nameRoman: 'JR Tozai Line',
        nameChinese: 'JR东西线',
        nameKorean: 'JR 도자이선',
        color: '#FF1493',
        lineType: 2,
        lineSymbols: [
          { symbol: 'H', color: '#FF1493', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162509,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'H',
              lineSymbolColor: '#FF1493',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'H-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 17208,
            typeId: 100,
            groupId: 468,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11629,
        nameShort: 'JR宝塚線',
        nameKatakana: 'タカラヅカセン',
        nameFull: '福知山線',
        nameRoman: 'JR Takarazuka Line',
        nameChinese: 'JR宝冢线',
        nameKorean: 'JR 다카라즈카선',
        color: '#FFCC00',
        lineType: 2,
        lineSymbols: [
          {
            symbol: 'G',
            color: '#FFBA00',
            shape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
          },
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162903,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '쓰카모토',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'G',
              lineSymbolColor: '#FFBA00',
              lineSymbolShape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
              stationNumber: 'G-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15282,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11625,
      nameShort: 'JR東西線',
      nameKatakana: 'トウザイセン',
      nameFull: 'JR東西線',
      nameRoman: 'JR Tozai Line',
      nameChinese: 'JR东西线',
      nameKorean: 'JR 도자이선',
      color: '#FF1493',
      lineType: 2,
      lineSymbols: [
        { symbol: 'H', color: '#FF1493', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1162509,
        groupId: 1160303,
        name: '尼崎',
        nameKatakana: 'アマガサキ',
        nameRoman: 'Amagasaki',
        nameChinese: '尼崎',
        nameKorean: '아마가사키',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '660-0808',
        address: '兵庫県尼崎市潮江一丁目1-1',
        latitude: 34.731791,
        longitude: 135.431685,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 28,
    postalCode: '660-0808',
    address: '兵庫県尼崎市潮江一丁目1-1',
    latitude: 34.731791,
    longitude: 135.431685,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'H',
        lineSymbolColor: '#FF1493',
        lineSymbolShape: 'REVERSED_SQUARE_WEST',
        stationNumber: 'H-49',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 17208,
      typeId: 100,
      groupId: 468,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 1162903,
    groupId: 1160303,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '쓰카모토',
    threeLetterCode: '',
    lines: [
      {
        id: 11603,
        nameShort: 'JR神戸線',
        nameKatakana: 'コウベセン',
        nameFull: '東海道本線',
        nameRoman: 'JR Kobe Line',
        nameChinese: 'JR神户线',
        nameKorean: 'JR 고베선',
        color: '#0072BC',
        lineType: 2,
        lineSymbols: [
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1160303,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'A',
              lineSymbolColor: '#0072BC',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'A-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15281,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11625,
        nameShort: 'JR東西線',
        nameKatakana: 'トウザイセン',
        nameFull: 'JR東西線',
        nameRoman: 'JR Tozai Line',
        nameChinese: 'JR东西线',
        nameKorean: 'JR 도자이선',
        color: '#FF1493',
        lineType: 2,
        lineSymbols: [
          { symbol: 'H', color: '#FF1493', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162509,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'H',
              lineSymbolColor: '#FF1493',
              lineSymbolShape: 'REVERSED_SQUARE_WEST',
              stationNumber: 'H-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 17208,
            typeId: 100,
            groupId: 468,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11629,
        nameShort: 'JR宝塚線',
        nameKatakana: 'タカラヅカセン',
        nameFull: '福知山線',
        nameRoman: 'JR Takarazuka Line',
        nameChinese: 'JR宝冢线',
        nameKorean: 'JR 다카라즈카선',
        color: '#FFCC00',
        lineType: 2,
        lineSymbols: [
          {
            symbol: 'G',
            color: '#FFBA00',
            shape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
          },
          { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1162903,
          groupId: 1160303,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '쓰카모토',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0808',
          address: '兵庫県尼崎市潮江一丁目1-1',
          latitude: 34.731791,
          longitude: 135.431685,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'G',
              lineSymbolColor: '#FFBA00',
              lineSymbolShape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
              stationNumber: 'G-49',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 15282,
            typeId: 100,
            groupId: 407,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11629,
      nameShort: 'JR宝塚線',
      nameKatakana: 'タカラヅカセン',
      nameFull: '福知山線',
      nameRoman: 'JR Takarazuka Line',
      nameChinese: 'JR宝冢线',
      nameKorean: 'JR 다카라즈카선',
      color: '#FFCC00',
      lineType: 2,
      lineSymbols: [
        {
          symbol: 'G',
          color: '#FFBA00',
          shape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
        },
        { symbol: 'A', color: '#0072BC', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1162903,
        groupId: 1160303,
        name: '尼崎',
        nameKatakana: 'アマガサキ',
        nameRoman: 'Amagasaki',
        nameChinese: '尼崎',
        nameKorean: '쓰카모토',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '660-0808',
        address: '兵庫県尼崎市潮江一丁目1-1',
        latitude: 34.731791,
        longitude: 135.431685,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 28,
    postalCode: '660-0808',
    address: '兵庫県尼崎市潮江一丁目1-1',
    latitude: 34.731791,
    longitude: 135.431685,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'G',
        lineSymbolColor: '#FFBA00',
        lineSymbolShape: 'REVERSED_SQUARE_WEST_DARK_TEXT',
        stationNumber: 'G-49',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 15282,
      typeId: 100,
      groupId: 407,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 3500109,
    groupId: 3500109,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: '',
    lines: [
      {
        id: 35001,
        nameShort: '阪神本線',
        nameKatakana: 'ハンシンホンセン',
        nameFull: '阪神本線',
        nameRoman: 'Hanshin Main Line',
        nameChinese: '',
        nameKorean: '',
        color: '#FFA00E',
        lineType: 2,
        lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
        status: 0,
        station: {
          id: 3500109,
          groupId: 3500109,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '661-0953',
          address: '兵庫県尼崎市東御園町93',
          latitude: 34.718634,
          longitude: 135.417309,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'HS',
              lineSymbolColor: '#1F64B1',
              lineSymbolShape: 'HANSHIN',
              stationNumber: 'HS-09',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 16735,
            typeId: 300,
            groupId: 453,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 25,
          railroadId: 35,
          nameShort: '阪神',
          nameKatakana: 'ハンシンデンテツ',
          nameFull: '阪神電気鉄道株式会社',
          nameEnglishShort: 'Hanshin',
          nameEnglishFull: 'Hanshin Electric Railway',
          url: 'http://rail.hanshin.co.jp/',
          type: 2,
          status: 0,
          name: '阪神電鉄',
        },
      },
      {
        id: 35002,
        nameShort: '阪神なんば線',
        nameKatakana: 'ハンシンナンバセン',
        nameFull: '阪神なんば線',
        nameRoman: 'Hanshin Namba Line',
        nameChinese: '',
        nameKorean: '',
        color: '#6BB5E6',
        lineType: 2,
        lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
        status: 0,
        station: {
          id: 3500207,
          groupId: 3500109,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '661-0953',
          address: '兵庫県尼崎市東御園町93',
          latitude: 34.718634,
          longitude: 135.417309,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'HS',
              lineSymbolColor: '#1F64B1',
              lineSymbolShape: 'HANSHIN',
              stationNumber: 'HS-09',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 6908,
            typeId: 300,
            groupId: 194,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 25,
          railroadId: 35,
          nameShort: '阪神',
          nameKatakana: 'ハンシンデンテツ',
          nameFull: '阪神電気鉄道株式会社',
          nameEnglishShort: 'Hanshin',
          nameEnglishFull: 'Hanshin Electric Railway',
          url: 'http://rail.hanshin.co.jp/',
          type: 2,
          status: 0,
          name: '阪神電鉄',
        },
      },
    ],
    line: {
      id: 35001,
      nameShort: '阪神本線',
      nameKatakana: 'ハンシンホンセン',
      nameFull: '阪神本線',
      nameRoman: 'Hanshin Main Line',
      nameChinese: '',
      nameKorean: '',
      color: '#FFA00E',
      lineType: 2,
      lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
      status: 0,
      station: {
        id: 3500109,
        groupId: 3500109,
        name: '尼崎',
        nameKatakana: 'アマガサキ',
        nameRoman: 'Amagasaki',
        nameChinese: '尼崎',
        nameKorean: '아마가사키',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '661-0953',
        address: '兵庫県尼崎市東御園町93',
        latitude: 34.718634,
        longitude: 135.417309,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 25,
        railroadId: 35,
        nameShort: '阪神',
        nameKatakana: 'ハンシンデンテツ',
        nameFull: '阪神電気鉄道株式会社',
        nameEnglishShort: 'Hanshin',
        nameEnglishFull: 'Hanshin Electric Railway',
        url: 'http://rail.hanshin.co.jp/',
        type: 2,
        status: 0,
        name: '阪神電鉄',
      },
    },
    prefectureId: 28,
    postalCode: '661-0953',
    address: '兵庫県尼崎市東御園町93',
    latitude: 34.718634,
    longitude: 135.417309,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'HS',
        lineSymbolColor: '#1F64B1',
        lineSymbolShape: 'HANSHIN',
        stationNumber: 'HS-09',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 16735,
      typeId: 300,
      groupId: 453,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 3500111,
    groupId: 3500111,
    name: '尼崎センタープール前',
    nameKatakana: 'アマガサキセンタープールマエ',
    nameRoman: 'Amagasaki-Centerpool-Mae',
    nameChinese: '尼崎汽艇比赛场前',
    nameKorean: '아마가사키 센터풀마에',
    threeLetterCode: '',
    lines: [
      {
        id: 35001,
        nameShort: '阪神本線',
        nameKatakana: 'ハンシンホンセン',
        nameFull: '阪神本線',
        nameRoman: 'Hanshin Main Line',
        nameChinese: '',
        nameKorean: '',
        color: '#FFA00E',
        lineType: 2,
        lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
        status: 0,
        station: {
          id: 3500111,
          groupId: 3500111,
          name: '尼崎センタープール前',
          nameKatakana: 'アマガサキセンタープールマエ',
          nameRoman: 'Amagasaki-Centerpool-Mae',
          nameChinese: '尼崎汽艇比赛场前',
          nameKorean: '아마가사키 센터풀마에',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '660-0082',
          address: '兵庫県尼崎市水明町３７３-６',
          latitude: 34.71776,
          longitude: 135.39504399999998,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'HS',
              lineSymbolColor: '#1F64B1',
              lineSymbolShape: 'HANSHIN',
              stationNumber: 'HS-11',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 16737,
            typeId: 300,
            groupId: 453,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 25,
          railroadId: 35,
          nameShort: '阪神',
          nameKatakana: 'ハンシンデンテツ',
          nameFull: '阪神電気鉄道株式会社',
          nameEnglishShort: 'Hanshin',
          nameEnglishFull: 'Hanshin Electric Railway',
          url: 'http://rail.hanshin.co.jp/',
          type: 2,
          status: 0,
          name: '阪神電鉄',
        },
      },
    ],
    line: {
      id: 35001,
      nameShort: '阪神本線',
      nameKatakana: 'ハンシンホンセン',
      nameFull: '阪神本線',
      nameRoman: 'Hanshin Main Line',
      nameChinese: '',
      nameKorean: '',
      color: '#FFA00E',
      lineType: 2,
      lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
      status: 0,
      station: {
        id: 3500111,
        groupId: 3500111,
        name: '尼崎センタープール前',
        nameKatakana: 'アマガサキセンタープールマエ',
        nameRoman: 'Amagasaki-Centerpool-Mae',
        nameChinese: '尼崎汽艇比赛场前',
        nameKorean: '아마가사키 센터풀마에',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '660-0082',
        address: '兵庫県尼崎市水明町３７３-６',
        latitude: 34.71776,
        longitude: 135.39504399999998,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 25,
        railroadId: 35,
        nameShort: '阪神',
        nameKatakana: 'ハンシンデンテツ',
        nameFull: '阪神電気鉄道株式会社',
        nameEnglishShort: 'Hanshin',
        nameEnglishFull: 'Hanshin Electric Railway',
        url: 'http://rail.hanshin.co.jp/',
        type: 2,
        status: 0,
        name: '阪神電鉄',
      },
    },
    prefectureId: 28,
    postalCode: '660-0082',
    address: '兵庫県尼崎市水明町３７３-６',
    latitude: 34.71776,
    longitude: 135.39504399999998,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'HS',
        lineSymbolColor: '#1F64B1',
        lineSymbolShape: 'HANSHIN',
        stationNumber: 'HS-11',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 16737,
      typeId: 300,
      groupId: 453,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 3500207,
    groupId: 3500109,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: '',
    lines: [
      {
        id: 35001,
        nameShort: '阪神本線',
        nameKatakana: 'ハンシンホンセン',
        nameFull: '阪神本線',
        nameRoman: 'Hanshin Main Line',
        nameChinese: '',
        nameKorean: '',
        color: '#FFA00E',
        lineType: 2,
        lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
        status: 0,
        station: {
          id: 3500109,
          groupId: 3500109,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '661-0953',
          address: '兵庫県尼崎市東御園町93',
          latitude: 34.718634,
          longitude: 135.417309,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'HS',
              lineSymbolColor: '#1F64B1',
              lineSymbolShape: 'HANSHIN',
              stationNumber: 'HS-09',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 16735,
            typeId: 300,
            groupId: 453,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 25,
          railroadId: 35,
          nameShort: '阪神',
          nameKatakana: 'ハンシンデンテツ',
          nameFull: '阪神電気鉄道株式会社',
          nameEnglishShort: 'Hanshin',
          nameEnglishFull: 'Hanshin Electric Railway',
          url: 'http://rail.hanshin.co.jp/',
          type: 2,
          status: 0,
          name: '阪神電鉄',
        },
      },
      {
        id: 35002,
        nameShort: '阪神なんば線',
        nameKatakana: 'ハンシンナンバセン',
        nameFull: '阪神なんば線',
        nameRoman: 'Hanshin Namba Line',
        nameChinese: '',
        nameKorean: '',
        color: '#6BB5E6',
        lineType: 2,
        lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
        status: 0,
        station: {
          id: 3500207,
          groupId: 3500109,
          name: '尼崎',
          nameKatakana: 'アマガサキ',
          nameRoman: 'Amagasaki',
          nameChinese: '尼崎',
          nameKorean: '아마가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 28,
          postalCode: '661-0953',
          address: '兵庫県尼崎市東御園町93',
          latitude: 34.718634,
          longitude: 135.417309,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'HS',
              lineSymbolColor: '#1F64B1',
              lineSymbolShape: 'HANSHIN',
              stationNumber: 'HS-09',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 6908,
            typeId: 300,
            groupId: 194,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 25,
          railroadId: 35,
          nameShort: '阪神',
          nameKatakana: 'ハンシンデンテツ',
          nameFull: '阪神電気鉄道株式会社',
          nameEnglishShort: 'Hanshin',
          nameEnglishFull: 'Hanshin Electric Railway',
          url: 'http://rail.hanshin.co.jp/',
          type: 2,
          status: 0,
          name: '阪神電鉄',
        },
      },
    ],
    line: {
      id: 35002,
      nameShort: '阪神なんば線',
      nameKatakana: 'ハンシンナンバセン',
      nameFull: '阪神なんば線',
      nameRoman: 'Hanshin Namba Line',
      nameChinese: '',
      nameKorean: '',
      color: '#6BB5E6',
      lineType: 2,
      lineSymbols: [{ symbol: 'HS', color: '#1F64B1', shape: 'HANSHIN' }],
      status: 0,
      station: {
        id: 3500207,
        groupId: 3500109,
        name: '尼崎',
        nameKatakana: 'アマガサキ',
        nameRoman: 'Amagasaki',
        nameChinese: '尼崎',
        nameKorean: '아마가사키',
        threeLetterCode: '',
        lines: [],
        prefectureId: 28,
        postalCode: '661-0953',
        address: '兵庫県尼崎市東御園町93',
        latitude: 34.718634,
        longitude: 135.417309,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 25,
        railroadId: 35,
        nameShort: '阪神',
        nameKatakana: 'ハンシンデンテツ',
        nameFull: '阪神電気鉄道株式会社',
        nameEnglishShort: 'Hanshin',
        nameEnglishFull: 'Hanshin Electric Railway',
        url: 'http://rail.hanshin.co.jp/',
        type: 2,
        status: 0,
        name: '阪神電鉄',
      },
    },
    prefectureId: 28,
    postalCode: '661-0953',
    address: '兵庫県尼崎市東御園町93',
    latitude: 34.718634,
    longitude: 135.417309,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'HS',
        lineSymbolColor: '#1F64B1',
        lineSymbolShape: 'HANSHIN',
        stationNumber: 'HS-09',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 6908,
      typeId: 300,
      groupId: 194,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
].map((s) => new Station(s));

export const OCHIAI_STATIONS_FROM_SEARCH: Station[] = [
  {
    id: 1110617,
    groupId: 1110617,
    name: '落合',
    nameKatakana: 'オチアイ',
    nameRoman: 'Ochiai',
    nameChinese: '落合',
    nameKorean: '오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 11106,
        nameShort: '根室本線',
        nameKatakana: 'ネムロホンセン',
        nameFull: '根室本線',
        nameRoman: 'Nemuro Main Line',
        nameChinese: '根室本线',
        nameKorean: '네무로 본선',
        color: '#F6989D',
        lineType: 2,
        lineSymbols: [
          { symbol: 'T', color: '#F6989D', shape: 'ROUND' },
          { symbol: 'K', color: '#8CC63E', shape: 'ROUND' },
          { symbol: 'A', color: '#F7931D', shape: 'ROUND' },
        ],
        status: 0,
        station: {
          id: 1110617,
          groupId: 1110617,
          name: '落合',
          nameKatakana: 'オチアイ',
          nameRoman: 'Ochiai',
          nameChinese: '落合',
          nameKorean: '오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 1,
          postalCode: '079-2551',
          address: '北海道空知郡南富良野町落合',
          latitude: 43.125055,
          longitude: 142.669104,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'T',
              lineSymbolColor: '#F6989D',
              lineSymbolShape: 'ROUND',
              stationNumber: 'T-37',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: false,
        },
        company: {
          id: 1,
          railroadId: 11,
          nameShort: 'JR北海道',
          nameKatakana: 'ジェイアールホッカイドウ',
          nameFull: '北海道旅客鉄道株式会社',
          nameEnglishShort: 'JR Hokkaido',
          nameEnglishFull: 'JR Hokkaido',
          url: 'http://www.jrhokkaido.co.jp/',
          type: 1,
          status: 0,
          name: 'JR北海道',
        },
      },
    ],
    line: {
      id: 11106,
      nameShort: '根室本線',
      nameKatakana: 'ネムロホンセン',
      nameFull: '根室本線',
      nameRoman: 'Nemuro Main Line',
      nameChinese: '根室本线',
      nameKorean: '네무로 본선',
      color: '#F6989D',
      lineType: 2,
      lineSymbols: [
        { symbol: 'T', color: '#F6989D', shape: 'ROUND' },
        { symbol: 'K', color: '#8CC63E', shape: 'ROUND' },
        { symbol: 'A', color: '#F7931D', shape: 'ROUND' },
      ],
      status: 0,
      station: {
        id: 1110617,
        groupId: 1110617,
        name: '落合',
        nameKatakana: 'オチアイ',
        nameRoman: 'Ochiai',
        nameChinese: '落合',
        nameKorean: '오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 1,
        postalCode: '079-2551',
        address: '北海道空知郡南富良野町落合',
        latitude: 43.125055,
        longitude: 142.669104,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: false,
      },
      company: {
        id: 1,
        railroadId: 11,
        nameShort: 'JR北海道',
        nameKatakana: 'ジェイアールホッカイドウ',
        nameFull: '北海道旅客鉄道株式会社',
        nameEnglishShort: 'JR Hokkaido',
        nameEnglishFull: 'JR Hokkaido',
        url: 'http://www.jrhokkaido.co.jp/',
        type: 1,
        status: 0,
        name: 'JR北海道',
      },
    },
    prefectureId: 1,
    postalCode: '079-2551',
    address: '北海道空知郡南富良野町落合',
    latitude: 43.125055,
    longitude: 142.669104,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'T',
        lineSymbolColor: '#F6989D',
        lineSymbolShape: 'ROUND',
        stationNumber: 'T-37',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: false,
  },
  {
    id: 1121707,
    groupId: 1121707,
    name: '陸前落合',
    nameKatakana: 'リクゼンオチアイ',
    nameRoman: 'Rikuzen-Ochiai',
    nameChinese: '陆前落合',
    nameKorean: '리쿠젠오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 11217,
        nameShort: '仙山線',
        nameKatakana: 'センザンセン',
        nameFull: '仙山線',
        nameRoman: 'Senzan Line',
        nameChinese: '仙山线',
        nameKorean: '센잔선',
        color: '#77DD00',
        lineType: 2,
        lineSymbols: [],
        status: 0,
        station: {
          id: 1121707,
          groupId: 1121707,
          name: '陸前落合',
          nameKatakana: 'リクゼンオチアイ',
          nameRoman: 'Rikuzen-Ochiai',
          nameChinese: '陆前落合',
          nameKorean: '리쿠젠오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 4,
          postalCode: '989-3125',
          address: '宮城県仙台市青葉区下愛子森下',
          latitude: 38.273379,
          longitude: 140.789896,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: false,
        },
        company: {
          id: 2,
          railroadId: 11,
          nameShort: 'JR東日本',
          nameKatakana: 'ジェイアールヒガシニホン',
          nameFull: '東日本旅客鉄道株式会社',
          nameEnglishShort: 'JR East',
          nameEnglishFull: 'JR East',
          url: 'http://www.jreast.co.jp/',
          type: 1,
          status: 0,
          name: 'JR東日本',
        },
      },
    ],
    line: {
      id: 11217,
      nameShort: '仙山線',
      nameKatakana: 'センザンセン',
      nameFull: '仙山線',
      nameRoman: 'Senzan Line',
      nameChinese: '仙山线',
      nameKorean: '센잔선',
      color: '#77DD00',
      lineType: 2,
      lineSymbols: [],
      status: 0,
      station: {
        id: 1121707,
        groupId: 1121707,
        name: '陸前落合',
        nameKatakana: 'リクゼンオチアイ',
        nameRoman: 'Rikuzen-Ochiai',
        nameChinese: '陆前落合',
        nameKorean: '리쿠젠오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 4,
        postalCode: '989-3125',
        address: '宮城県仙台市青葉区下愛子森下',
        latitude: 38.273379,
        longitude: 140.789896,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: false,
      },
      company: {
        id: 2,
        railroadId: 11,
        nameShort: 'JR東日本',
        nameKatakana: 'ジェイアールヒガシニホン',
        nameFull: '東日本旅客鉄道株式会社',
        nameEnglishShort: 'JR East',
        nameEnglishFull: 'JR East',
        url: 'http://www.jreast.co.jp/',
        type: 1,
        status: 0,
        name: 'JR東日本',
      },
    },
    prefectureId: 4,
    postalCode: '989-3125',
    address: '宮城県仙台市青葉区下愛子森下',
    latitude: 38.273379,
    longitude: 140.789896,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: false,
  },
  {
    id: 1141121,
    groupId: 1141121,
    name: '落合川',
    nameKatakana: 'オチアイガワ',
    nameRoman: 'Ochiaigawa',
    nameChinese: '落合川',
    nameKorean: '오치아이가와',
    threeLetterCode: '',
    lines: [
      {
        id: 11411,
        nameShort: '中央本線',
        nameKatakana: 'チュウオウホンセン',
        nameFull: '中央本線',
        nameRoman: 'Chuo Main Line',
        nameChinese: '中央本线',
        nameKorean: '주오 본선',
        color: '#307097',
        lineType: 2,
        lineSymbols: [
          {
            symbol: 'CF',
            color: '#307097',
            shape: 'HALF_SQUARE_WITHOUT_ROUND',
          },
        ],
        status: 0,
        station: {
          id: 1141121,
          groupId: 1141121,
          name: '落合川',
          nameKatakana: 'オチアイガワ',
          nameRoman: 'Ochiaigawa',
          nameChinese: '落合川',
          nameKorean: '오치아이가와',
          threeLetterCode: '',
          lines: [],
          prefectureId: 21,
          postalCode: '508-0006',
          address: '岐阜県中津川市落合',
          latitude: 35.525116000000004,
          longitude: 137.530034,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
        },
        company: {
          id: 3,
          railroadId: 11,
          nameShort: 'JR東海',
          nameKatakana: 'ジェイアールトウカイ',
          nameFull: '東海旅客鉄道株式会社',
          nameEnglishShort: 'JR Central',
          nameEnglishFull: 'JR Central',
          url: 'http://jr-central.co.jp/',
          type: 1,
          status: 0,
          name: 'JR東海',
        },
      },
    ],
    line: {
      id: 11411,
      nameShort: '中央本線',
      nameKatakana: 'チュウオウホンセン',
      nameFull: '中央本線',
      nameRoman: 'Chuo Main Line',
      nameChinese: '中央本线',
      nameKorean: '주오 본선',
      color: '#307097',
      lineType: 2,
      lineSymbols: [
        { symbol: 'CF', color: '#307097', shape: 'HALF_SQUARE_WITHOUT_ROUND' },
      ],
      status: 0,
      station: {
        id: 1141121,
        groupId: 1141121,
        name: '落合川',
        nameKatakana: 'オチアイガワ',
        nameRoman: 'Ochiaigawa',
        nameChinese: '落合川',
        nameKorean: '오치아이가와',
        threeLetterCode: '',
        lines: [],
        prefectureId: 21,
        postalCode: '508-0006',
        address: '岐阜県中津川市落合',
        latitude: 35.525116000000004,
        longitude: 137.530034,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 3,
        railroadId: 11,
        nameShort: 'JR東海',
        nameKatakana: 'ジェイアールトウカイ',
        nameFull: '東海旅客鉄道株式会社',
        nameEnglishShort: 'JR Central',
        nameEnglishFull: 'JR Central',
        url: 'http://jr-central.co.jp/',
        type: 1,
        status: 0,
        name: 'JR東海',
      },
    },
    prefectureId: 21,
    postalCode: '508-0006',
    address: '岐阜県中津川市落合',
    latitude: 35.525116000000004,
    longitude: 137.530034,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
  },
  {
    id: 1163416,
    groupId: 1163416,
    name: '美作落合',
    nameKatakana: 'ミマサカオチアイ',
    nameRoman: 'Mimasaka-Ochiai',
    nameChinese: '美作落合',
    nameKorean: '미마사카오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 11634,
        nameShort: '姫新線',
        nameKatakana: 'キシンセン',
        nameFull: '姫新線',
        nameRoman: 'Kishin Line',
        nameChinese: '姬新线',
        nameKorean: '기신선',
        color: '#800080',
        lineType: 2,
        lineSymbols: [
          { symbol: 'K', color: '#800080', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1163416,
          groupId: 1163416,
          name: '美作落合',
          nameKatakana: 'ミマサカオチアイ',
          nameRoman: 'Mimasaka-Ochiai',
          nameChinese: '美作落合',
          nameKorean: '미마사카오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 33,
          postalCode: '719-3105',
          address: '岡山県真庭市西原',
          latitude: 35.02318,
          longitude: 133.759656,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 11595,
            typeId: 100,
            groupId: 309,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11634,
      nameShort: '姫新線',
      nameKatakana: 'キシンセン',
      nameFull: '姫新線',
      nameRoman: 'Kishin Line',
      nameChinese: '姬新线',
      nameKorean: '기신선',
      color: '#800080',
      lineType: 2,
      lineSymbols: [
        { symbol: 'K', color: '#800080', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1163416,
        groupId: 1163416,
        name: '美作落合',
        nameKatakana: 'ミマサカオチアイ',
        nameRoman: 'Mimasaka-Ochiai',
        nameChinese: '美作落合',
        nameKorean: '미마사카오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 33,
        postalCode: '719-3105',
        address: '岡山県真庭市西原',
        latitude: 35.02318,
        longitude: 133.759656,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 33,
    postalCode: '719-3105',
    address: '岡山県真庭市西原',
    latitude: 35.02318,
    longitude: 133.759656,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 11595,
      typeId: 100,
      groupId: 309,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 1170618,
    groupId: 1170618,
    name: '備後落合',
    nameKatakana: 'ビンゴオチアイ',
    nameRoman: 'Bingo-Ochiai',
    nameChinese: '备后落合',
    nameKorean: '빈고오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 11706,
        nameShort: '木次線',
        nameKatakana: 'キスキセン',
        nameFull: '木次線',
        nameRoman: 'Kisuki Line',
        nameChinese: '木次线',
        nameKorean: '기스키선',
        color: '#339966',
        lineType: 2,
        lineSymbols: [
          { symbol: 'E', color: '#339966', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1170618,
          groupId: 1170618,
          name: '備後落合',
          nameKatakana: 'ビンゴオチアイ',
          nameRoman: 'Bingo-Ochiai',
          nameChinese: '备后落合',
          nameKorean: '빈고오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 34,
          postalCode: '729-5613',
          address: '広島県庄原市西城町八鳥',
          latitude: 35.001167,
          longitude: 133.148296,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: false,
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11714,
        nameShort: '芸備線',
        nameKatakana: 'ゲイビセン',
        nameFull: '芸備線',
        nameRoman: 'Geibi Line',
        nameChinese: '艺备线',
        nameKorean: '게이비선',
        color: '#00CED1',
        lineType: 2,
        lineSymbols: [
          { symbol: 'P', color: '#00CED1', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1171413,
          groupId: 1170618,
          name: '備後落合',
          nameKatakana: 'ビンゴオチアイ',
          nameRoman: 'Bingo-Ochiai',
          nameChinese: '备后落合',
          nameKorean: '빈고오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 34,
          postalCode: '729-5613',
          address: '広島県庄原市西城町八鳥',
          latitude: 35.001167,
          longitude: 133.148296,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 19439,
            typeId: 100,
            groupId: 529,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11706,
      nameShort: '木次線',
      nameKatakana: 'キスキセン',
      nameFull: '木次線',
      nameRoman: 'Kisuki Line',
      nameChinese: '木次线',
      nameKorean: '기스키선',
      color: '#339966',
      lineType: 2,
      lineSymbols: [
        { symbol: 'E', color: '#339966', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1170618,
        groupId: 1170618,
        name: '備後落合',
        nameKatakana: 'ビンゴオチアイ',
        nameRoman: 'Bingo-Ochiai',
        nameChinese: '备后落合',
        nameKorean: '빈고오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 34,
        postalCode: '729-5613',
        address: '広島県庄原市西城町八鳥',
        latitude: 35.001167,
        longitude: 133.148296,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: false,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 34,
    postalCode: '729-5613',
    address: '広島県庄原市西城町八鳥',
    latitude: 35.001167,
    longitude: 133.148296,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: false,
  },
  {
    id: 1171413,
    groupId: 1170618,
    name: '備後落合',
    nameKatakana: 'ビンゴオチアイ',
    nameRoman: 'Bingo-Ochiai',
    nameChinese: '备后落合',
    nameKorean: '빈고오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 11706,
        nameShort: '木次線',
        nameKatakana: 'キスキセン',
        nameFull: '木次線',
        nameRoman: 'Kisuki Line',
        nameChinese: '木次线',
        nameKorean: '기스키선',
        color: '#339966',
        lineType: 2,
        lineSymbols: [
          { symbol: 'E', color: '#339966', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1170618,
          groupId: 1170618,
          name: '備後落合',
          nameKatakana: 'ビンゴオチアイ',
          nameRoman: 'Bingo-Ochiai',
          nameChinese: '备后落合',
          nameKorean: '빈고오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 34,
          postalCode: '729-5613',
          address: '広島県庄原市西城町八鳥',
          latitude: 35.001167,
          longitude: 133.148296,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: false,
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
      {
        id: 11714,
        nameShort: '芸備線',
        nameKatakana: 'ゲイビセン',
        nameFull: '芸備線',
        nameRoman: 'Geibi Line',
        nameChinese: '艺备线',
        nameKorean: '게이비선',
        color: '#00CED1',
        lineType: 2,
        lineSymbols: [
          { symbol: 'P', color: '#00CED1', shape: 'REVERSED_SQUARE_WEST' },
        ],
        status: 0,
        station: {
          id: 1171413,
          groupId: 1170618,
          name: '備後落合',
          nameKatakana: 'ビンゴオチアイ',
          nameRoman: 'Bingo-Ochiai',
          nameChinese: '备后落合',
          nameKorean: '빈고오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 34,
          postalCode: '729-5613',
          address: '広島県庄原市西城町八鳥',
          latitude: 35.001167,
          longitude: 133.148296,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 19439,
            typeId: 100,
            groupId: 529,
            name: '普通',
            nameKatakana: 'フツウ',
            nameRoman: 'Local',
            nameChinese: '慢车',
            nameKorean: '보통',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 4,
          railroadId: 11,
          nameShort: 'JR西日本',
          nameKatakana: 'ジェイアールニシニホン',
          nameFull: '西日本旅客鉄道株式会社',
          nameEnglishShort: 'JR West',
          nameEnglishFull: 'JR West',
          url: 'http://www.westjr.co.jp/',
          type: 1,
          status: 0,
          name: 'JR西日本',
        },
      },
    ],
    line: {
      id: 11714,
      nameShort: '芸備線',
      nameKatakana: 'ゲイビセン',
      nameFull: '芸備線',
      nameRoman: 'Geibi Line',
      nameChinese: '艺备线',
      nameKorean: '게이비선',
      color: '#00CED1',
      lineType: 2,
      lineSymbols: [
        { symbol: 'P', color: '#00CED1', shape: 'REVERSED_SQUARE_WEST' },
      ],
      status: 0,
      station: {
        id: 1171413,
        groupId: 1170618,
        name: '備後落合',
        nameKatakana: 'ビンゴオチアイ',
        nameRoman: 'Bingo-Ochiai',
        nameChinese: '备后落合',
        nameKorean: '빈고오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 34,
        postalCode: '729-5613',
        address: '広島県庄原市西城町八鳥',
        latitude: 35.001167,
        longitude: 133.148296,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: 1,
        status: 0,
        name: 'JR西日本',
      },
    },
    prefectureId: 34,
    postalCode: '729-5613',
    address: '広島県庄原市西城町八鳥',
    latitude: 35.001167,
    longitude: 133.148296,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 19439,
      typeId: 100,
      groupId: 529,
      name: '普通',
      nameKatakana: 'フツウ',
      nameRoman: 'Local',
      nameChinese: '慢车',
      nameKorean: '보통',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 2200703,
    groupId: 2200703,
    name: '下落合',
    nameKatakana: 'シモオチアイ',
    nameRoman: 'Shimo-Ochiai',
    nameChinese: '下落合',
    nameKorean: '시모오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 22007,
        nameShort: '西武新宿線',
        nameKatakana: 'セイブシンジュクセン',
        nameFull: '西武新宿線',
        nameRoman: 'Seibu Shinjuku Line',
        nameChinese: '西武新宿线',
        nameKorean: '세이부 신주쿠선',
        color: '#00A6C0',
        lineType: 2,
        lineSymbols: [
          { symbol: 'SS', color: '#00A6C0', shape: 'HALF_SQUARE_DARK_TEXT' },
        ],
        status: 0,
        station: {
          id: 2200703,
          groupId: 2200703,
          name: '下落合',
          nameKatakana: 'シモオチアイ',
          nameRoman: 'Shimo-Ochiai',
          nameChinese: '下落合',
          nameKorean: '시모오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 13,
          postalCode: '161-0033',
          address: '東京都新宿区下落合１-１６-１',
          latitude: 35.715846,
          longitude: 139.695391,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'SS',
              lineSymbolColor: '#00A6C0',
              lineSymbolShape: 'HALF_SQUARE_DARK_TEXT',
              stationNumber: 'SS-03',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 8193,
            typeId: 301,
            groupId: 219,
            name: '各駅停車',
            nameKatakana: 'カクエキテイシャ',
            nameRoman: 'Local',
            nameChinese: '每站停车',
            nameKorean: '각역정차',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 12,
          railroadId: 22,
          nameShort: '西武',
          nameKatakana: 'セイブテツドウ',
          nameFull: '西武鉄道株式会社',
          nameEnglishShort: 'Seibu',
          nameEnglishFull: 'Seibu Railway',
          url: 'http://www.seibu-group.co.jp/railways/',
          type: 2,
          status: 0,
          name: '西武鉄道',
        },
      },
    ],
    line: {
      id: 22007,
      nameShort: '西武新宿線',
      nameKatakana: 'セイブシンジュクセン',
      nameFull: '西武新宿線',
      nameRoman: 'Seibu Shinjuku Line',
      nameChinese: '西武新宿线',
      nameKorean: '세이부 신주쿠선',
      color: '#00A6C0',
      lineType: 2,
      lineSymbols: [
        { symbol: 'SS', color: '#00A6C0', shape: 'HALF_SQUARE_DARK_TEXT' },
      ],
      status: 0,
      station: {
        id: 2200703,
        groupId: 2200703,
        name: '下落合',
        nameKatakana: 'シモオチアイ',
        nameRoman: 'Shimo-Ochiai',
        nameChinese: '下落合',
        nameKorean: '시모오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 13,
        postalCode: '161-0033',
        address: '東京都新宿区下落合１-１６-１',
        latitude: 35.715846,
        longitude: 139.695391,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 12,
        railroadId: 22,
        nameShort: '西武',
        nameKatakana: 'セイブテツドウ',
        nameFull: '西武鉄道株式会社',
        nameEnglishShort: 'Seibu',
        nameEnglishFull: 'Seibu Railway',
        url: 'http://www.seibu-group.co.jp/railways/',
        type: 2,
        status: 0,
        name: '西武鉄道',
      },
    },
    prefectureId: 13,
    postalCode: '161-0033',
    address: '東京都新宿区下落合１-１６-１',
    latitude: 35.715846,
    longitude: 139.695391,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'SS',
        lineSymbolColor: '#00A6C0',
        lineSymbolShape: 'HALF_SQUARE_DARK_TEXT',
        stationNumber: 'SS-03',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 8193,
      typeId: 301,
      groupId: 219,
      name: '各駅停車',
      nameKatakana: 'カクエキテイシャ',
      nameRoman: 'Local',
      nameChinese: '每站停车',
      nameKorean: '각역정차',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 2800402,
    groupId: 2800402,
    name: '落合',
    nameKatakana: 'オチアイ',
    nameRoman: 'Ochiai',
    nameChinese: '落合',
    nameKorean: '오치아이',
    threeLetterCode: '',
    lines: [
      {
        id: 28004,
        nameShort: '東京メトロ東西線',
        nameKatakana: 'トウキョウメトロトウザイセン',
        nameFull: '東京メトロ東西線',
        nameRoman: 'Tokyo Metro Tozai Line',
        nameChinese: '东西线',
        nameKorean: '도자이선',
        color: '#00A7DB',
        lineType: 3,
        lineSymbols: [{ symbol: 'T', color: '#00A7DB', shape: 'ROUND' }],
        status: 0,
        station: {
          id: 2800402,
          groupId: 2800402,
          name: '落合',
          nameKatakana: 'オチアイ',
          nameRoman: 'Ochiai',
          nameChinese: '落合',
          nameKorean: '오치아이',
          threeLetterCode: '',
          lines: [],
          prefectureId: 13,
          postalCode: '161-0034',
          address: '東京都新宿区上落合２-１３-７',
          latitude: 35.710976,
          longitude: 139.687284,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'T',
              lineSymbolColor: '#00A7DB',
              lineSymbolShape: 'ROUND',
              stationNumber: 'T-02',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: true,
          trainType: {
            id: 2609,
            typeId: 101,
            groupId: 88,
            name: '各駅停車',
            nameKatakana: 'カクエキテイシャ',
            nameRoman: 'Local',
            nameChinese: '每站停车',
            nameKorean: '각역정차',
            color: '#1F63C6',
            lines: [],
            direction: 0,
            kind: 0,
          },
        },
        company: {
          id: 18,
          railroadId: 28,
          nameShort: '東京メトロ',
          nameKatakana: 'トウキョウメトロ',
          nameFull: '東京地下鉄株式会社',
          nameEnglishShort: 'Tokyo Metro',
          nameEnglishFull: 'Tokyo Metro',
          url: 'http://www.tokyometro.jp/',
          type: 2,
          status: 0,
          name: '東京メトロ',
        },
      },
    ],
    line: {
      id: 28004,
      nameShort: '東京メトロ東西線',
      nameKatakana: 'トウキョウメトロトウザイセン',
      nameFull: '東京メトロ東西線',
      nameRoman: 'Tokyo Metro Tozai Line',
      nameChinese: '东西线',
      nameKorean: '도자이선',
      color: '#00A7DB',
      lineType: 3,
      lineSymbols: [{ symbol: 'T', color: '#00A7DB', shape: 'ROUND' }],
      status: 0,
      station: {
        id: 2800402,
        groupId: 2800402,
        name: '落合',
        nameKatakana: 'オチアイ',
        nameRoman: 'Ochiai',
        nameChinese: '落合',
        nameKorean: '오치아이',
        threeLetterCode: '',
        lines: [],
        prefectureId: 13,
        postalCode: '161-0034',
        address: '東京都新宿区上落合２-１３-７',
        latitude: 35.710976,
        longitude: 139.687284,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: true,
      },
      company: {
        id: 18,
        railroadId: 28,
        nameShort: '東京メトロ',
        nameKatakana: 'トウキョウメトロ',
        nameFull: '東京地下鉄株式会社',
        nameEnglishShort: 'Tokyo Metro',
        nameEnglishFull: 'Tokyo Metro',
        url: 'http://www.tokyometro.jp/',
        type: 2,
        status: 0,
        name: '東京メトロ',
      },
    },
    prefectureId: 13,
    postalCode: '161-0034',
    address: '東京都新宿区上落合２-１３-７',
    latitude: 35.710976,
    longitude: 139.687284,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'T',
        lineSymbolColor: '#00A7DB',
        lineSymbolShape: 'ROUND',
        stationNumber: 'T-02',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: true,
    trainType: {
      id: 2609,
      typeId: 101,
      groupId: 88,
      name: '各駅停車',
      nameKatakana: 'カクエキテイシャ',
      nameRoman: 'Local',
      nameChinese: '每站停车',
      nameKorean: '각역정차',
      color: '#1F63C6',
      lines: [],
      direction: 0,
      kind: 0,
    },
  },
  {
    id: 9930133,
    groupId: 9930133,
    name: '落合南長崎',
    nameKatakana: 'オチアイミナミナガサキ',
    nameRoman: 'Ochiai-minami-nagasaki',
    nameChinese: '落合南长崎',
    nameKorean: '오치아이미나미나가사키',
    threeLetterCode: '',
    lines: [
      {
        id: 99301,
        nameShort: '都営大江戸線',
        nameKatakana: 'トエイオオエドセン',
        nameFull: '都営大江戸線',
        nameRoman: 'Toei Oedo Line',
        nameChinese: '都营大江户线',
        nameKorean: '도에이 오에도선',
        color: '#B6007A',
        lineType: 3,
        lineSymbols: [{ symbol: 'E', color: '#B6007A', shape: 'ROUND' }],
        status: 0,
        station: {
          id: 9930133,
          groupId: 9930133,
          name: '落合南長崎',
          nameKatakana: 'オチアイミナミナガサキ',
          nameRoman: 'Ochiai-minami-nagasaki',
          nameChinese: '落合南长崎',
          nameKorean: '오치아이미나미나가사키',
          threeLetterCode: '',
          lines: [],
          prefectureId: 13,
          postalCode: '161-0031',
          address: '東京都新宿区西落合３-１-１８',
          latitude: 35.723608,
          longitude: 139.683303,
          openedAt: '0000-00-00',
          closedAt: '0000-00-00',
          status: 0,
          stationNumbers: [
            {
              lineSymbol: 'E',
              lineSymbolColor: '#B6007A',
              lineSymbolShape: 'ROUND',
              stationNumber: 'E-33',
            },
          ],
          stopCondition: 0,
          distance: 0,
          hasTrainTypes: false,
        },
        company: {
          id: 119,
          railroadId: 99,
          nameShort: '都営交通',
          nameKatakana: 'トウキョウトコウツウキョク',
          nameFull: '東京都交通局',
          nameEnglishShort: 'Toei Transportation',
          nameEnglishFull: 'Toei Transportation',
          url: 'http://www.kotsu.metro.tokyo.jp/',
          type: 0,
          status: 0,
          name: '東京都交通局',
        },
      },
    ],
    line: {
      id: 99301,
      nameShort: '都営大江戸線',
      nameKatakana: 'トエイオオエドセン',
      nameFull: '都営大江戸線',
      nameRoman: 'Toei Oedo Line',
      nameChinese: '都营大江户线',
      nameKorean: '도에이 오에도선',
      color: '#B6007A',
      lineType: 3,
      lineSymbols: [{ symbol: 'E', color: '#B6007A', shape: 'ROUND' }],
      status: 0,
      station: {
        id: 9930133,
        groupId: 9930133,
        name: '落合南長崎',
        nameKatakana: 'オチアイミナミナガサキ',
        nameRoman: 'Ochiai-minami-nagasaki',
        nameChinese: '落合南长崎',
        nameKorean: '오치아이미나미나가사키',
        threeLetterCode: '',
        lines: [],
        prefectureId: 13,
        postalCode: '161-0031',
        address: '東京都新宿区西落合３-１-１８',
        latitude: 35.723608,
        longitude: 139.683303,
        openedAt: '0000-00-00',
        closedAt: '0000-00-00',
        status: 0,
        stationNumbers: [],
        stopCondition: 0,
        distance: 0,
        hasTrainTypes: false,
      },
      company: {
        id: 119,
        railroadId: 99,
        nameShort: '都営交通',
        nameKatakana: 'トウキョウトコウツウキョク',
        nameFull: '東京都交通局',
        nameEnglishShort: 'Toei Transportation',
        nameEnglishFull: 'Toei Transportation',
        url: 'http://www.kotsu.metro.tokyo.jp/',
        type: 0,
        status: 0,
        name: '東京都交通局',
      },
    },
    prefectureId: 13,
    postalCode: '161-0031',
    address: '東京都新宿区西落合３-１-１８',
    latitude: 35.723608,
    longitude: 139.683303,
    openedAt: '0000-00-00',
    closedAt: '0000-00-00',
    status: 0,
    stationNumbers: [
      {
        lineSymbol: 'E',
        lineSymbolColor: '#B6007A',
        lineSymbolShape: 'ROUND',
        stationNumber: 'E-33',
      },
    ],
    stopCondition: 0,
    distance: 0,
    hasTrainTypes: false,
  },
].map((s) => new Station(s));
