import {
  CompanyType,
  LineType,
  OperationStatus,
  type Station,
  StopCondition,
} from '~/@types/graphql';

/**
 * Fixture data for testing station search and grouping functionality.
 * These fixtures contain properly typed data with all required GraphQL fields.
 */

export const AMAGASAKI_STATIONS_FROM_SEARCH: Station[] = [
  // JR West - groupId 1160303
  {
    __typename: 'Station',
    id: 1160303,
    groupId: 1160303,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11603,
      nameShort: 'JR神戸線',
      nameKatakana: 'コウベセン',
      nameFull: '東海道本線',
      nameRoman: 'JR Kobe Line',
      nameChinese: 'JR神户线',
      nameKorean: 'JR 고베선',
      color: '#0072BC',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: CompanyType.Jr,
        status: OperationStatus.InOperation,
        name: 'JR西日本',
      },
    },
    prefectureId: 28,
    postalCode: '660-0808',
    address: '兵庫県尼崎市潮江一丁目1-1',
    latitude: 34.731791,
    longitude: 135.431685,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: true,
    trainType: undefined,
  },
  // Hanshin - groupId 3500109
  {
    __typename: 'Station',
    id: 3500109,
    groupId: 3500109,
    name: '尼崎',
    nameKatakana: 'アマガサキ',
    nameRoman: 'Amagasaki',
    nameChinese: '尼崎',
    nameKorean: '아마가사키',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 35001,
      nameShort: '阪神本線',
      nameKatakana: 'ハンシンホンセン',
      nameFull: '阪神本線',
      nameRoman: 'Hanshin Main Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#FFA00E',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 25,
        railroadId: 35,
        nameShort: '阪神',
        nameKatakana: 'ハンシンデンテツ',
        nameFull: '阪神電気鉄道株式会社',
        nameEnglishShort: 'Hanshin',
        nameEnglishFull: 'Hanshin Electric Railway',
        url: 'http://rail.hanshin.co.jp/',
        type: CompanyType.Private,
        status: OperationStatus.InOperation,
        name: '阪神電鉄',
      },
    },
    prefectureId: 28,
    postalCode: '661-0953',
    address: '兵庫県尼崎市東御園町93',
    latitude: 34.718634,
    longitude: 135.417309,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: true,
    trainType: undefined,
  },
  // Unique station - groupId 3500111
  {
    __typename: 'Station',
    id: 3500111,
    groupId: 3500111,
    name: '尼崎センタープール前',
    nameKatakana: 'アマガサキセンタープールマエ',
    nameRoman: 'Amagasaki-Centerpool-Mae',
    nameChinese: '尼崎汽艇比赛场前',
    nameKorean: '아마가사키 센터풀마에',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 35001,
      nameShort: '阪神本線',
      nameKatakana: 'ハンシンホンセン',
      nameFull: '阪神本線',
      nameRoman: 'Hanshin Main Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#FFA00E',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 25,
        railroadId: 35,
        nameShort: '阪神',
        nameKatakana: 'ハンシンデンテツ',
        nameFull: '阪神電気鉄道株式会社',
        nameEnglishShort: 'Hanshin',
        nameEnglishFull: 'Hanshin Electric Railway',
        url: 'http://rail.hanshin.co.jp/',
        type: CompanyType.Private,
        status: OperationStatus.InOperation,
        name: '阪神電鉄',
      },
    },
    prefectureId: 28,
    postalCode: '660-0082',
    address: '兵庫県尼崎市水明町３７３-６',
    latitude: 34.71776,
    longitude: 135.39504399999998,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: true,
    trainType: undefined,
  },
];

export const OCHIAI_STATIONS_FROM_SEARCH: Station[] = [
  // 落合 (Hokkaido) - prefectureId 1
  {
    __typename: 'Station',
    id: 1110617,
    groupId: 1110617,
    name: '落合',
    nameKatakana: 'オチアイ',
    nameRoman: 'Ochiai',
    nameChinese: '落合',
    nameKorean: '오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11106,
      nameShort: '根室本線',
      nameKatakana: 'ネムロホンセン',
      nameFull: '根室本線',
      nameRoman: 'Nemuro Main Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#2CA5A0',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 1,
        railroadId: 1,
        nameShort: 'JR北海道',
        nameKatakana: 'ジェイアールホッカイドウ',
        nameFull: '北海道旅客鉄道株式会社',
        nameEnglishShort: 'JR Hokkaido',
        nameEnglishFull: 'JR Hokkaido',
        url: 'http://www.jrhokkaido.co.jp/',
        type: CompanyType.Jr,
        status: OperationStatus.InOperation,
        name: 'JR北海道',
      },
    },
    prefectureId: 1,
    postalCode: undefined,
    address: undefined,
    latitude: 43.076512,
    longitude: 142.768356,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 陸前落合 (Miyagi) - unique name
  {
    __typename: 'Station',
    id: 1120301,
    groupId: 1120301,
    name: '陸前落合',
    nameKatakana: 'リクゼンオチアイ',
    nameRoman: 'Rikuzen-Ochiai',
    nameChinese: '陸前落合',
    nameKorean: '리쿠젠오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11203,
      nameShort: '仙石線',
      nameKatakana: 'センセキセン',
      nameFull: '仙石線',
      nameRoman: 'Senseki Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#58B947',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 2,
        railroadId: 2,
        nameShort: 'JR東日本',
        nameKatakana: 'ジェイアールヒガシニホン',
        nameFull: '東日本旅客鉄道株式会社',
        nameEnglishShort: 'JR East',
        nameEnglishFull: 'JR East',
        url: 'http://www.jreast.co.jp/',
        type: CompanyType.Jr,
        status: OperationStatus.InOperation,
        name: 'JR東日本',
      },
    },
    prefectureId: 4,
    postalCode: undefined,
    address: undefined,
    latitude: 38.366667,
    longitude: 141.016667,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 落合川 (Tokyo) - unique name
  {
    __typename: 'Station',
    id: 9917710,
    groupId: 9917710,
    name: '落合川',
    nameKatakana: 'オチアイガワ',
    nameRoman: 'Ochiaigawa',
    nameChinese: '落合川',
    nameKorean: '오치아이가와',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 99177,
      nameShort: '多摩都市モノレール線',
      nameKatakana: 'タマトシモノレールセン',
      nameFull: '多摩都市モノレール線',
      nameRoman: 'Tama Toshi Monorail Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#17B1BE',
      lineType: LineType.MonorailOrAgt,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 156,
        railroadId: 991,
        nameShort: '多摩都市モノレール',
        nameKatakana: 'タマトシモノレール',
        nameFull: '多摩都市モノレール株式会社',
        nameEnglishShort: 'Tama Monorail',
        nameEnglishFull: 'Tama Monorail',
        url: 'http://www.tama-monorail.co.jp/',
        type: CompanyType.Private,
        status: OperationStatus.InOperation,
        name: '多摩都市モノレール',
      },
    },
    prefectureId: 13,
    postalCode: undefined,
    address: undefined,
    latitude: 35.714167,
    longitude: 139.416667,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 美作落合 (Okayama) - unique name
  {
    __typename: 'Station',
    id: 1132606,
    groupId: 1132606,
    name: '美作落合',
    nameKatakana: 'ミマサカオチアイ',
    nameRoman: 'Mimasaka-Ochiai',
    nameChinese: '美作落合',
    nameKorean: '미마사카오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11326,
      nameShort: '姫新線',
      nameKatakana: 'キシンセン',
      nameFull: '姫新線',
      nameRoman: 'Kishin Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#B48A76',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: CompanyType.Jr,
        status: OperationStatus.InOperation,
        name: 'JR西日本',
      },
    },
    prefectureId: 33,
    postalCode: undefined,
    address: undefined,
    latitude: 35.083333,
    longitude: 133.566667,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 備後落合 (Hiroshima) - unique name
  {
    __typename: 'Station',
    id: 1132607,
    groupId: 1132607,
    name: '備後落合',
    nameKatakana: 'ビンゴオチアイ',
    nameRoman: 'Bingo-Ochiai',
    nameChinese: '備後落合',
    nameKorean: '빙고오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11326,
      nameShort: '芸備線',
      nameKatakana: 'ゲイビセン',
      nameFull: '芸備線',
      nameRoman: 'Geibi Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#A39DBB',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 4,
        railroadId: 11,
        nameShort: 'JR西日本',
        nameKatakana: 'ジェイアールニシニホン',
        nameFull: '西日本旅客鉄道株式会社',
        nameEnglishShort: 'JR West',
        nameEnglishFull: 'JR West',
        url: 'http://www.westjr.co.jp/',
        type: CompanyType.Jr,
        status: OperationStatus.InOperation,
        name: 'JR西日本',
      },
    },
    prefectureId: 34,
    postalCode: undefined,
    address: undefined,
    latitude: 34.966667,
    longitude: 133.016667,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 下落合 (Tokyo) - unique name
  {
    __typename: 'Station',
    id: 1161210,
    groupId: 1161210,
    name: '下落合',
    nameKatakana: 'シモオチアイ',
    nameRoman: 'Shimo-Ochiai',
    nameChinese: '下落合',
    nameKorean: '시모오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 11612,
      nameShort: '西武新宿線',
      nameKatakana: 'セイブシンジュクセン',
      nameFull: '西武新宿線',
      nameRoman: 'Seibu Shinjuku Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#FFDD00',
      lineType: LineType.Normal,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 23,
        railroadId: 31,
        nameShort: '西武',
        nameKatakana: 'セイブ',
        nameFull: '西武鉄道株式会社',
        nameEnglishShort: 'Seibu',
        nameEnglishFull: 'Seibu Railway',
        url: 'http://www.seibu-group.co.jp/railways/',
        type: CompanyType.Major,
        status: OperationStatus.InOperation,
        name: '西武鉄道',
      },
    },
    prefectureId: 13,
    postalCode: undefined,
    address: undefined,
    latitude: 35.716667,
    longitude: 139.683333,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 落合 (Tokyo) - prefectureId 13
  {
    __typename: 'Station',
    id: 2800312,
    groupId: 2800312,
    name: '落合',
    nameKatakana: 'オチアイ',
    nameRoman: 'Ochiai',
    nameChinese: '落合',
    nameKorean: '오치아이',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 28003,
      nameShort: '東京メトロ東西線',
      nameKatakana: 'トウザイセン',
      nameFull: '東京メトロ東西線',
      nameRoman: 'Tokyo Metro Tozai Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#00A7DB',
      lineType: LineType.Subway,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 18,
        railroadId: 28,
        nameShort: '東京メトロ',
        nameKatakana: 'トウキョウメトロ',
        nameFull: '東京地下鉄株式会社',
        nameEnglishShort: 'Tokyo Metro',
        nameEnglishFull: 'Tokyo Metro',
        url: 'http://www.tokyometro.jp/',
        type: CompanyType.Major,
        status: OperationStatus.InOperation,
        name: '東京メトロ',
      },
    },
    prefectureId: 13,
    postalCode: undefined,
    address: undefined,
    latitude: 35.720833,
    longitude: 139.685,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
  // 落合南長崎 (Tokyo) - unique name
  {
    __typename: 'Station',
    id: 2800512,
    groupId: 2800512,
    name: '落合南長崎',
    nameKatakana: 'オチアイミナミナガサキ',
    nameRoman: 'Ochiai-minami-nagasaki',
    nameChinese: '落合南長崎',
    nameKorean: '오치아이미나미나가사키',
    threeLetterCode: undefined,
    lines: [],
    line: {
      __typename: 'Line',
      id: 28005,
      nameShort: '都営大江戸線',
      nameKatakana: 'オオエドセン',
      nameFull: '都営地下鉄大江戸線',
      nameRoman: 'Toei Oedo Line',
      nameChinese: undefined,
      nameKorean: undefined,
      color: '#E5007F',
      lineType: LineType.Subway,
      lineSymbols: [],
      status: OperationStatus.InOperation,
      station: undefined,
      trainType: undefined,
      averageDistance: undefined,
      company: {
        __typename: 'Company',
        id: 19,
        railroadId: 29,
        nameShort: '都営地下鉄',
        nameKatakana: 'トエイチカテツ',
        nameFull: '東京都交通局',
        nameEnglishShort: 'Toei',
        nameEnglishFull: 'Toei Subway',
        url: 'http://www.kotsu.metro.tokyo.jp/',
        type: CompanyType.OtherCompany,
        status: OperationStatus.InOperation,
        name: '東京都交通局',
      },
    },
    prefectureId: 13,
    postalCode: undefined,
    address: undefined,
    latitude: 35.722222,
    longitude: 139.682778,
    openedAt: undefined,
    closedAt: undefined,
    status: OperationStatus.InOperation,
    stationNumbers: [],
    stopCondition: StopCondition.All,
    distance: 0,
    hasTrainTypes: false,
    trainType: undefined,
  },
];
