export const HEADER_CONTENT_TRANSITION_INTERVAL = 5000; // ms
export const HEADER_CONTENT_TRANSITION_DELAY = 250; // ms
export const BOTTOM_CONTENT_TRANSITION_INTERVAL =
  HEADER_CONTENT_TRANSITION_INTERVAL * 1.5; // ms
export const APPROACHING_THRESHOLD = 600; // m
export const ARRIVED_THRESHOLD = 100; // m
export const BAD_ACCURACY_THRESHOLD = 1000; // m
export const OMIT_JR_THRESHOLD = 3; // これ以上JR線があったら「JR線」で省略しよう
export const JR_LINE_MAX_ID = 6;
