# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  def increment_version_code(gradle_build: 'app/build.gradle')
    sh %Q{cd ../ && echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' #{gradle_build})" > #{gradle_build} && cd -}
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    increment_version_code(gradle_build: "app/build.gradle")
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      release_notes: "自動配信ビルド"
    )
    slack(
      message: "App successfully released!",
      payload: {
        "Build Date" => Time.new.to_s,
        "Platform" => "App distribution",
        "Become a tester": "https://appdistribution.firebase.dev/i/6ab9aad46ead5823"
      },
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
