# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  def increment_version_code(gradle_build: 'app/build.gradle')
    sh %Q{cd ../ && echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' #{gradle_build})" > #{gradle_build} && cd -}
  end

  desc "Bump version number"
  lane :bump_version do
    increment_version_code(gradle_build: "app/build.gradle")
  end
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["SIGNING_STORE_FILE"],
        "android.injected.signing.store.password" => ENV["SIGNING_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["SIGNING_KEY_PASSWORD"],
      }
    )
    firebase_app_distribution(
      app: ENV["ANDROID_FIREBASE_APP_ID"],
      release_notes: "自動配信ビルド",
      groups: "Android",
      service_credentials_file: ENV["GOOGLE_APPLICATION_CREDENTIALS"],
      # ↓全面サービス再開したときに使う
      # android_artifact_type: "AAB"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
